/**
 * check.ts — `pnpm check`
 *
 * Everything that can be wrong with this exhibition without the build failing.
 *
 * The asset pipeline is happy to publish a museum whose floor plan points at a
 * room that is not there, a work whose scan is a photograph of a frame, or a
 * corpus that is four sentences long — all of them produce output, and all of
 * them are only visible by walking the corridor and noticing. So this reads
 * the authored records and says what is wrong with them, in one pass, offline,
 * before anything is built.
 *
 * It checks the atlas graph the same way, because that file is authored by
 * hand and regenerated by nothing, and it exercises the Commons scorer against
 * the failures it exists to catch — that function is the one place a silent
 * mistake ends with the wrong painting on a wall under a real placard.
 *
 * Exit code 1 if anything failed; warnings do not fail the run.
 */
import fs from 'node:fs';
import path from 'node:path';
import { artworkData } from './lib/paths.ts';
import { loadMuseumWithWorks, museumOrder, regionsFor } from './lib/records.ts';
import { aspectError, expectedAspect, keywords, scoreCandidate } from './fetch-images.ts';
import type { ArtworkRecord } from './lib/records.ts';

const failures: string[] = [];
const warnings: string[] = [];

const fail = (msg: string) => failures.push(msg);
const warn = (msg: string) => warnings.push(msg);

/* ── the records ────────────────────────────────────────────────────────── */

const seen = new Set<string>();
let works = 0;

for (const museumId of museumOrder()) {
  let museum;
  let records;
  try {
    ({ museum, works: records } = loadMuseumWithWorks(museumId));
  } catch (err) {
    // a work listed by a museum but missing from its collection throws here,
    // which is the single most common authoring mistake
    fail((err as Error).message);
    continue;
  }
  works += records.length;

  const plan = museum.plan as { rooms: Array<{ id: string; name: string; artworkIndex: number }> };
  const rooms = plan.rooms.filter((r) => r.artworkIndex >= 0);
  if (rooms.length !== records.length) {
    fail(
      `${museumId}: the floor plan has ${rooms.length} rooms with works in them but the ` +
        `museum hangs ${records.length}`,
    );
  }
  for (const room of rooms) {
    if (room.artworkIndex >= records.length) {
      fail(`${museumId}: plan room "${room.id}" points at work ${room.artworkIndex}, which is not hung`);
    }
  }
  const roomIds = new Set(plan.rooms.map((r) => r.id));
  if (roomIds.size !== plan.rooms.length) fail(`${museumId}: two rooms in the floor plan share an id`);

  const style = museum.style as { bays: number };
  if (style.bays < records.length / 2) {
    warn(`${museumId}: ${records.length} works over ${style.bays} bays will stack tightly`);
  }

  for (const record of records) {
    if (seen.has(record.id)) fail(`${record.id} is hung in more than one museum`);
    seen.add(record.id);
    checkRecord(museumId, record);
  }
}

function checkRecord(museumId: string, r: ArtworkRecord) {
  const where = `${museumId}/${r.id}`;
  for (const field of ['artist', 'title', 'year', 'medium', 'dimensions', 'labelText'] as const) {
    if (!String(r[field] ?? '').trim()) fail(`${where}: "${field}" is empty`);
  }
  if (!/^#[0-9a-fA-F]{6}$/.test(r.accentColor)) {
    fail(`${where}: accentColor "${r.accentColor}" is not a six-digit hex colour`);
  }
  if (r.heroFocus) {
    const [x, y] = r.heroFocus;
    if (!(x >= 0 && x <= 1 && y >= 0 && y <= 1)) {
      fail(`${where}: heroFocus ${JSON.stringify(r.heroFocus)} is outside the picture`);
    }
  }

  // a label nobody can read is worse than no label; a note of two lines makes
  // a thin corpus, and a thin corpus is a painting that repeats itself
  if (r.labelText.length < 120) warn(`${where}: the wall label is only ${r.labelText.length} characters`);
  if (r.extendedNote.length < 400) warn(`${where}: the extended note is only ${r.extendedNote.length} characters`);

  for (const region of regionsFor(r)) {
    const [x0, y0, x1, y1] = region.box;
    const inside = [x0, y0, x1, y1].every((n) => n >= 0 && n <= 1);
    if (!inside || x1 <= x0 || y1 <= y0) {
      fail(`${where}: Thread Pull region "${region.id}" has an impossible box ${JSON.stringify(region.box)}`);
    }
    if (!region.text.trim()) fail(`${where}: Thread Pull region "${region.id}" has no passage`);
  }

  const scan = path.join(artworkData(r.id), 'source.jpg');
  if (!fs.existsSync(scan)) {
    warn(`${where}: no scan — it will render a procedural stand-in (pnpm fetch:images)`);
    return;
  }
  // the scan's proportions against the catalogue: a frame or a gallery wall
  // around the canvas shows up here as a number long before anyone sees it
  const credit = path.join(artworkData(r.id), 'image-credit.json');
  if (fs.existsSync(credit)) {
    const c = JSON.parse(fs.readFileSync(credit, 'utf8')) as { width?: number; height?: number };
    const err = aspectError(expectedAspect(r.dimensions), c.width ?? 0, c.height ?? 0);
    if (err > 0.1) {
      warn(
        `${where}: the scan is ${(err * 100).toFixed(0)}% off the catalogued proportions — ` +
          `check it is not framed or cropped`,
      );
    }
  }
}

/* ── the atlas graph ────────────────────────────────────────────────────── */

/*
 * public/atlas.json is authored by hand and regenerated by nothing, so it is
 * the one file that silently falls out of step when a work is swapped: a work
 * with no painter never joins the map, and a link to an entity that no longer
 * exists is an edge the view draws to nowhere.
 */
{
  const atlas = JSON.parse(fs.readFileSync(path.join('public', 'atlas.json'), 'utf8')) as {
    entities: Array<{ id: string; kind: string; label: string }>;
    works: Record<string, string>;
    links: Array<{ a: string; b: string; kind: string }>;
  };
  const entities = new Set(atlas.entities.map((e) => e.id));
  if (entities.size !== atlas.entities.length) fail('atlas: two entities share an id');

  for (const [work, painter] of Object.entries(atlas.works)) {
    if (!seen.has(work)) fail(`atlas: "${work}" is on the map but hung in no museum`);
    if (!entities.has(painter)) fail(`atlas: "${work}" is attributed to "${painter}", who is not an entity`);
  }
  for (const id of seen) {
    if (!(id in atlas.works)) warn(`atlas: "${id}" is hung but has no painter on the map`);
  }
  const known = new Set([...entities, ...Object.keys(atlas.works)]);
  for (const link of atlas.links) {
    for (const end of [link.a, link.b]) {
      if (!known.has(end)) fail(`atlas: a "${link.kind}" link points at "${end}", which does not exist`);
    }
  }
}

/* ── the scorer ─────────────────────────────────────────────────────────── */

/**
 * The cases that actually put a wrong picture on a wall. Each one is a file
 * Commons really returns for the work named, and the plain reproduction has to
 * beat all of them.
 */
const wanted = keywords('Johannes Vermeer The Lacemaker La Dentellière');
const expected = expectedAspect('24.5 × 21 cm');
const plain = scoreCandidate(
  'File:Johannes Vermeer - The Lacemaker - WGA24689.jpg',
  1800,
  2100,
  'image/jpeg',
  wanted,
  expected,
);
const rivals: Array<[string, string, number, number]> = [
  ['a photograph of it in its frame', 'File:Vermeer The Lacemaker framed, Louvre.jpg', 2584, 2736],
  ['a gallery snapshot', 'File:The Lacemaker on display in the museum gallery.jpg', 3000, 2000],
  ['a detail', 'File:Vermeer Lacemaker detail of hands.jpg', 2000, 1400],
  ['an engraving after it', 'File:The Lacemaker engraving after Vermeer.jpg', 1600, 1900],
  ['a different painting entirely', 'File:Cathedral of Saint Nicholas at dusk.jpg', 2400, 1600],
];
for (const [what, file, w, h] of rivals) {
  const got = scoreCandidate(file, w, h, 'image/jpeg', wanted, expected);
  if (got >= plain) {
    fail(`scorer: ${what} (${got.toFixed(0)}) is not beaten by the plain reproduction (${plain.toFixed(0)})`);
  }
}
if (plain < 30) fail(`scorer: the plain reproduction scores ${plain.toFixed(0)}, under the accept threshold`);

// the proportions test, which is what catches a frame the file name hides
if (aspectError(expectedAspect('92 × 73 cm'), 2000, 1600) < 0.1) {
  fail('scorer: a landscape file passed the aspect test for a portrait canvas');
}
if (aspectError(expectedAspect('92 × 73 cm'), 1600, 2000) > 0.02) {
  fail('scorer: the right proportions were reported as wrong');
}

/* ── the verdict ────────────────────────────────────────────────────────── */

console.log(`\nchecked ${seen.size} works across ${museumOrder().length} museums\n`);
for (const w of warnings) console.log(`  ⚠ ${w}`);
for (const f of failures) console.log(`  ✗ ${f}`);
if (warnings.length) console.log(`\n${warnings.length} warning${warnings.length === 1 ? '' : 's'}`);
if (failures.length) {
  console.log(`${failures.length} failure${failures.length === 1 ? '' : 's'}\n`);
  process.exit(1);
}
console.log(`\nnothing to fix — ${works} works ready to build.\n`);
